
- name: Install nginx dependencies
  apt:
    name: ["nginx", "dirmngr", "gnupg"]

- name: Prepare nginx.conf
  template:
    src: app.conf.j2
    dest: "/etc/nginx/sites-enabled/default"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Prepare puma systemd
  template:
    src: puma.service.j2
    dest: "/etc/systemd/system/puma.service"
    owner: root
    group: root
    mode: 0644
    backup: yes
