# ---

- name: Install Ruby Dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - curl
    - g++
    - gcc
    - autoconf
    - automake
    - bison
    - libc6-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libsqlite3-dev
    - libtool
    - libyaml-dev
    - make
    - pkg-config
    - sqlite3
    - zlib1g-dev
    - libgmp-dev
    - libreadline-dev
    - libssl-dev


- name: Download Ruby source
  get_url:
    url: https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.2.tar.gz
    dest: /root

- name: tar -xf ruby-2.7.2.tar.gz
  shell: "tar -xf ruby-2.7.2.tar.gz"

- name: ./configure
  command: "./configure"
  args:
    chdir: ruby-2.7.2/

- name: make
  command: "make"
  args:
    chdir: ruby-2.7.2/

- name: sudo make install
  command: "sudo make install"
  args:
    chdir: ruby-2.7.2/
