---

- name: "Execute node-setup_{{ node.version.major }}.x.sh"
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash"
  args:
    chdir: /tmp/

- name: Install node and set version
  become: yes
  become_user: root
  shell: "source /root/.nvm/nvm.sh && nvm install 14.4.0"
  args:
    executable: /bin/bash

- name: Curl
  shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"

- name: Echo
  shell: "echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"

- name: npm install yarn
  npm:
    name: yarn
    global: yes
  environment:
    PATH: "/root/.nvm/versions/node/v14.4.0/bin:{{ ansible_env.PATH }}"
