- name: echo
  shell: "echo 'deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main' > /etc/apt/sources.list.d/pgdg.list"

- name: wget
  shell: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"

- name: Install postgresql
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql
    - libpq-dev

- name: Edit /etc/postgresql/10/main/pg_hba.conf
  lineinfile:
    dest: /etc/postgresql/10/main/pg_hba.conf
    owner: root
    group: root
    mode: 0644
    create: yes
    regexp: "^local   all             postgres"
    line: "local   all             postgres trust"

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
